/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Connexion (void);
GtkWidget* create_Admin (void);
GtkWidget* create_Utilisateur (void);
GtkWidget* create_ajouteruser (void);
GtkWidget* create_modifieruser (void);
GtkWidget* create_G_election (void);
GtkWidget* create_ajouter_g_election (void);
GtkWidget* create_modifier_G_election (void);
GtkWidget* create_supprimer (void);
GtkWidget* create_supprimer_liste (void);
GtkWidget* create_stats (void);
GtkWidget* create_vote (void);
GtkWidget* create_modifier_liste (void);
GtkWidget* create_afficher_liste_electorale (void);
GtkWidget* create_ajout_liste (void);
GtkWidget* create_menu_liste_electorale (void);
GtkWidget* create_gesObs (void);
GtkWidget* create_ajoutObs_window (void);
GtkWidget* create_suppObs_window (void);
GtkWidget* create_modifObs (void);
GtkWidget* create_dialogNObs (void);
GtkWidget* create_StatHatem (void);
GtkWidget* create_principal (void);
GtkWidget* create_supprimer_bu (void);
GtkWidget* create_ajouter (void);
GtkWidget* create_modifier (void);
GtkWidget* create_stat (void);
